

# This file was *autogenerated* from the file sol.sage
from sage.all_cmdline import *   # import sage library

_sage_const_99061670249353652702595159229088680425828208953931838069069584252923270946291 = Integer(99061670249353652702595159229088680425828208953931838069069584252923270946291); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_43190960452218023575787899214023014938926631792651638044680168600989609069200 = Integer(43190960452218023575787899214023014938926631792651638044680168600989609069200); _sage_const_20971936269255296908588589778128791635639992476076894152303569022736123671173 = Integer(20971936269255296908588589778128791635639992476076894152303569022736123671173); _sage_const_87360200456784002948566700858113190957688355783112995047798140117594305287669 = Integer(87360200456784002948566700858113190957688355783112995047798140117594305287669); _sage_const_6082896373499126624029343293750138460137531774473450341235217699497602895121 = Integer(6082896373499126624029343293750138460137531774473450341235217699497602895121); _sage_const_8 = Integer(8); _sage_const_0 = Integer(0); _sage_const_16 = Integer(16)
from factordb import factordb
import hashlib
from Crypto.Cipher import AES
from Crypto.Util.number import inverse
from Crypto.Util.Padding import pad, unpad

#Our p is unknown
#p = getPrime(pbits)
#a = 1
#b = 4
#E = EllipticCurve(GF(p), [a,b])

#We can easily find the p from the output.txt:
#99061670249353652702595159229088680425828208953931838069069584252923270946291
p = _sage_const_99061670249353652702595159229088680425828208953931838069069584252923270946291 
a = _sage_const_1 
b = _sage_const_4 
E = EllipticCurve(GF(p), [a,b])

#The generator :
G=E(_sage_const_43190960452218023575787899214023014938926631792651638044680168600989609069200  , _sage_const_20971936269255296908588589778128791635639992476076894152303569022736123671173 )

#From the output we have a_x and b_x: 
#a_x = [na]G[0] na is unknown
a_x = _sage_const_87360200456784002948566700858113190957688355783112995047798140117594305287669 
#b_x = [nb]G[0] nb is unknown
b_x = _sage_const_6082896373499126624029343293750138460137531774473450341235217699497602895121 

B = E.lift_x(b_x)
print(B)
#Here we must get the na:
A = E.lift_x(a_x)
#we will use the pohling hellman method which is based on crt
o = G.order()
n = factordb.FactorDB(o)
n.connect()
factors = n.get_factor_list()[:_sage_const_8 ]
n = []
r = []
m = _sage_const_1 
for mod in factors:
    g2 = G*(o//mod)
    q2 = A*(o//mod)
    rem = discrete_log(q2, g2, operation='+')
    r.append(rem)
    n.append(mod)
    m *= mod
na = crt(r, n)
S = na*B
sha1 = hashlib.sha1()
sha1.update(str(S[_sage_const_0 ]).encode('ascii'))
key = sha1.digest()[:_sage_const_16 ]
iv = bytes.fromhex("ceb34a8c174d77136455971f08641cc5")
ct = bytes.fromhex("b503bf04df71cfbd3f464aec2083e9b79c825803a4d4a43697889ad29eb75453")
cipher = AES.new(key, AES.MODE_CBC, iv)
pt = unpad(cipher.decrypt(ct),_sage_const_16 ).decode()
print(pt)

